
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin123}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
